const supabaseURL = "https://kqtzvhtjjcitwnihlxzk.supabase.co";
const supabaseAnonKey =
    "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImtxdHp2aHRqamNpdHduaWhseHprIiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTY4NjE3MzkzMiwiZXhwIjoyMDAxNzQ5OTMyfQ.fTx7TgCn6T01fRpXFalvF9HkgwwYtB7oCJ-Ow6SO14E";
